# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '2 10 1,18 * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.5"
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: DeletePosts
      env:
        COOKIEKEY1: '${{ secrets.COOKIEKEY1 }}'
        COOKIEKEY2: '${{ secrets.COOKIEKEY2 }}'
          
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python DeleteMyHistory.py 
        
      
